language: node_js
node_js:
  - '12'
sudo: required

services:
  - docker

install:
  - npm install

before_script:
  - npm install grunt-cli -g

script:
  - npm run lint
  - npm run coverage
  - npm run build
  - codecov

after_success:
  - REGEXP="release\s[0-9]+\.[0-9]+\.[0-9]+";
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [[ "$TRAVIS_COMMIT_MESSAGE" =~ $REGEXP ]]; then
    grunt build;
    fi
